#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-kxml2
Version  : 2.2.2
Release  : 2
URL      : https://repo1.maven.org/maven2/net/sf/kxml/kxml2/2.2.2/kxml2-2.2.2.jar
Source0  : https://repo1.maven.org/maven2/net/sf/kxml/kxml2/2.2.2/kxml2-2.2.2.jar
Source1  : https://repo1.maven.org/maven2/net/sf/kxml/kxml2/2.2.2/kxml2-2.2.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: mvn-kxml2-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-kxml2 package.
Group: Data

%description data
data components for the mvn-kxml2 package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/kxml/kxml2/2.2.2
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/net/sf/kxml/kxml2/2.2.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/kxml/kxml2/2.2.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/sf/kxml/kxml2/2.2.2


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/net/sf/kxml/kxml2/2.2.2/kxml2-2.2.2.jar
/usr/share/java/.m2/repository/net/sf/kxml/kxml2/2.2.2/kxml2-2.2.2.pom
